<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\WeekCalendarTray.Core\WeekCalendarTray.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>WeekCalendarTray</AssemblyName>
    <Product>Week Calendar Tray</Product>
    <Company>Week Calendar Tray</Company>
    <Version>1.2.1</Version>
    <FileVersion>1.2.1.0</FileVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

</Project>
